apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evmos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GauravKandhari/project.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://x.y.z.q #private cluster endpoint. You have to change it accordingly
    namespace: evmos
