apiVersion: v1
kind: Secret
metadata:
  name: test-private-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: test-private-cluster
  server: https://x.y.z.q  #Private cluster endpoint to monitor the cluster
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<Encoded CA Certificate of the private cluster"
      }
    }
